apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.service.name }}
spec:
  ports:
    - port: 3306
  selector:
    app: maria-db

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webserver.service.name }}
spec:
  selector:
    app: deno-webserver
  ports:
    - protocol: TCP
      port: {{ .Values.webserver.service.port }}
      targetPort: 8080
  type: {{ .Values.webserver.service.type }}